spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee-department
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: testing
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8084




